#!/usr/bin/env python3
"""Generate the day-5 OFFICE scene: a 30 x 20 m multi-room building where 180 s of exploration
does not saturate coverage (the validation room saturates, day 4).

    python3 docker/sim/tools/gen_office_world.py           # write files
    python3 docker/sim/tools/gen_office_world.py --check   # verify they match

Writes (all generated -- do not edit by hand):
    docker/sim/worlds/office.sdf
    docker/sim/models/office_scene/{model.config, model.sdf, materials/textures/*.png}

Geometry: docker/tools/closed_loop/scenes.py OFFICE (single source of truth, also used by the GT
coverage / clearance / watchdog tools). Rendering, lighting, physics and textures are those of the
validation scene (gen_validation_world.py: emissive textures, shadows off, same texture generator,
one unique seed per surface).
"""
from __future__ import annotations

import argparse, hashlib, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "docker", "tools", "closed_loop"))
from gen_validation_world import texture  # noqa: E402
from scenes import OFFICE, OFFICE_ENVELOPE  # noqa: E402

OUT_WORLD = os.path.join(ROOT, "docker/sim/worlds/office.sdf")
OUT_MODEL = os.path.join(ROOT, "docker/sim/models/office_scene")
WORLD_NAME = "office"


def material(tex: str) -> str:
    return f"""        <material>
          <diffuse>1 1 1 1</diffuse>
          <emissive>0.55 0.55 0.55 1</emissive>
          <pbr><metal>
            <albedo_map>model://office_scene/materials/textures/{tex}</albedo_map>
            <emissive_map>model://office_scene/materials/textures/{tex}</emissive_map>
            <metalness>0.0</metalness><roughness>1.0</roughness>
          </metal></pbr>
        </material>
"""


def solid_link(name, x, y, z, sx, sy, sz) -> str:
    return f"""    <link name="{name}">
      <pose>{x} {y} {z} 0 0 0</pose>
      <collision name="c"><geometry><box><size>{sx} {sy} {sz}</size></box></geometry></collision>
      <visual name="v">
        <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
{material(name + ".png")}      </visual>
    </link>
"""


def build() -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    x0, x1, y0, y1, _ = OFFICE_ENVELOPE
    # floor tiles of ~10 x 10 m, one texture each (a single 30 m plane would stretch the texels 3x)
    tiles = []
    for i, (a, b) in enumerate([(x0 - 1, 6.0), (6.0, 16.0), (16.0, x1 + 1)]):
        for j, (c, d) in enumerate([(y0 - 1, 0.0), (0.0, y1 + 1)]):
            tiles.append((f"floor_{i}{j}", (a + b) / 2, (c + d) / 2, b - a, d - c))
    names = [t[0] for t in tiles] + [s[0] for s in OFFICE]
    assert len(set(names)) == len(names)
    for k, n in enumerate(names):
        files[f"materials/textures/{n}.png"] = texture(2000 + k)
    links = ["""    <link name="ground">
      <collision name="c"><geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry></collision>
    </link>
"""]
    for n, cx, cy, sx, sy in tiles:
        links.append(f"""    <link name="{n}">
      <pose>{cx} {cy} 0 0 0 0</pose>
      <visual name="v">
        <geometry><plane><normal>0 0 1</normal><size>{sx} {sy}</size></plane></geometry>
{material(n + ".png")}      </visual>
    </link>
""")
    for (n, x, y, z, sx, sy, sz) in OFFICE:
        links.append(solid_link(n, x, y, z, sx, sy, sz))
    files["model.sdf"] = ("<?xml version=\"1.0\"?>\n<!-- GENERATED by docker/sim/tools/gen_office_world.py -- do not edit. -->\n"
                          "<sdf version=\"1.9\">\n  <model name=\"office_scene\">\n    <static>true</static>\n"
                          + "".join(links) + "  </model>\n</sdf>\n").encode()
    files["model.config"] = b"""<?xml version="1.0"?>
<!-- GENERATED by docker/sim/tools/gen_office_world.py -- do not edit. -->
<model>
  <name>office_scene</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>Day-5 office scene: 30 x 20 m, corridor + 6 rooms (SIMULATION ONLY).</description>
</model>
"""
    world = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by docker/sim/tools/gen_office_world.py -- do not edit.
     Physics, gravity, magnetic field, sun and spherical coordinates are copied
     from PX4's forest.sdf; scenery and lighting differ (PATCHES.md s49, s74). -->
<sdf version="1.9">
  <world name="{WORLD_NAME}">
    <physics type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>250</real_time_update_rate>
    </physics>
    <gravity>0 0 -9.81</gravity>
    <magnetic_field>6e-06 2.3e-05 -4.2e-05</magnetic_field>
    <atmosphere type="adiabatic"/>
    <scene>
      <grid>false</grid>
      <ambient>0.4 0.4 0.4 1</ambient>
      <background>0.7 0.7 0.7 1</background>
      <shadows>false</shadows>
    </scene>
    <include>
      <uri>model://office_scene</uri>
      <name>office_scene</name>
      <pose>0 0 0 0 0 0</pose>
    </include>
    <light name="sunUTC" type="directional">
      <pose>0 0 500 0 -0 0</pose>
      <cast_shadows>true</cast_shadows>
      <intensity>1</intensity>
      <direction>0.001 0.625 -0.78</direction>
      <diffuse>0.904 0.904 0.904 1</diffuse>
      <specular>0.271 0.271 0.271 1</specular>
      <attenuation><range>2000</range><linear>0</linear><constant>1</constant><quadratic>0</quadratic></attenuation>
      <spot><inner_angle>0</inner_angle><outer_angle>0</outer_angle><falloff>0</falloff></spot>
    </light>
    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>47.397971057728974</latitude_deg>
      <longitude_deg> 8.546163739800146</longitude_deg>
      <elevation>0</elevation>
    </spherical_coordinates>
  </world>
</sdf>
"""
    files["__world__"] = world.encode()
    return files


def target(rel: str) -> str:
    return OUT_WORLD if rel == "__world__" else os.path.join(OUT_MODEL, rel)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    files = build()
    bad = 0
    for rel, data in files.items():
        p = target(rel)
        if a.check:
            ok = os.path.exists(p) and open(p, "rb").read() == data
            bad += not ok
            print(f"  {'ok   ' if ok else 'DIFF '} {os.path.relpath(p, ROOT)}")
        else:
            os.makedirs(os.path.dirname(p), exist_ok=True)
            open(p, "wb").write(data)
            print(f"  wrote {os.path.relpath(p, ROOT)}  ({len(data)} B, sha {hashlib.sha256(data).hexdigest()[:10]})")
    if a.check:
        print("all generated files match" if not bad else f"{bad} file(s) differ -- regenerate")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
